import {
  AmaliyFan,
  Byd,
  Chevrolet,
  Giz,
  Logo,
  NurTex,
  SamAuto,
  Tdtu,
  Unesco,
} from "../../assets/img/img";

export const uselink = [
  {
    id: 7,
    link: "https://www.giz.de/",
    img: Giz,
    title: {
      uz: "GIZ",
      ru: "GIZ",
      en: "GIZ",
      de: "GIZ",
      zh: "GIZ厂",
    },
  },
  {
    id: 8,
    link: "https://www.unesco.org/ru",
    img: Unesco,
    title: {
      uz: "YUNESKO",
      ru: "ЮНЕСКО",
      en: "UNESCO",
      de: "UNESCO",
      zh: "联合国教科文组织",
    },
  },
  {
    id: 1,
    link: "https://bydfactory.uz/",
    img: Byd,
    title: {
      uz: "BYD UZBEKISTAN FACTORY",
      ru: "Фабрика BYD Узбекистан",
      en: "BYD UZBEKISTAN FACTORY",
      de: "BYD USBEKISTAN FABRIK",
      zh: "比亚迪乌兹别克斯坦工厂",
    },
  },
  {
    id: 2,
    link: "https://samauto.uz/",
    img: SamAuto,
    title: {
      uz: "SamAuto",
      ru: "СамАвто",
      en: "SamAuto",
      de: "SamAuto",
      zh: "SamAuto",
    },
  },
  {
    id: 3,
    link: "https://chevrolet.uz/",
    img: Chevrolet,
    title: {
      uz: "Chevrolet Uz",
      ru: "Шевроле Узбекистан",
      en: "Chevrolet Uz",
      de: "Chevrolet Usbekistan",
      zh: "雪佛兰乌兹别克斯坦",
    },
  },
  {
    id: 4,
    link: "https://www.tdtu.uz",
    img: Tdtu,
    title: {
      uz: "TDTU Universiteti",
      ru: "ТДТУ Университет",
      en: "TDTU University",
      de: "TDTU Universität",
      zh: "TDTU 大学",
    },
  },
  {
    id: 5,
    link: "https://utas.uz/",
    img: AmaliyFan,
    title: {
      uz: "Toshkent Amaliy Fablar Universitesi",
      ru: "Ташкентский университет прикладных наук",
      en: "Tashkent University of Applied Sciences",
      de: "Taschkent Universität für angewandte Wissenschaften",
      zh: "塔什干应用科学大学",
    },
  },
  {
    id: 6,
    link: "https://www.instagram.com/nurtex_uz/",
    img: NurTex,
    title: {
      uz: "NurTex",
      ru: "НурТех",
      en: "NurTex",
      de: "NurTex",
      zh: "NurTex",
    },
  },
];
